CREATE TABLE IF NOT EXISTS users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_name   VARCHAR(255)                            NOT NULL,
    first_name  VARCHAR(255)                            NOT NULL,
    middle_name VARCHAR(255),
    birth_date  TIMESTAMP WITHOUT TIME ZONE,
    email       VARCHAR(255) UNIQUE                     NOT NULL,
    phone       VARCHAR(15) UNIQUE                      NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_phone UNIQUE (phone)
);
